name: Publishing & Versioning

on:
  push:
    branches:
      - 'main'
      - 'release/[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: To set repository-specific username/email configuration
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - if: github.ref_name != 'master'
        run: npm run release -- --preRelease=rc --npm.tag=next
      - if: github.ref_name == 'master'
        run: npm run release
